services:
  frontend:
    build: .
    container_name: angular-frontend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4200:4200"
    command: sh -c "npm install &&  ng serve --host 0.0.0.0"
